# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    default_locale: en_GB
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    mailer:
        dsn: '%env(MAILER_DSN)%'
        message_bus: false
    #esi: true
    #fragments: true
    trusted_proxies: ['127.0.0.1', 'REMOTE_ADDR']
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
