twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/tailwind_theme.html.twig'
    globals:
        app_data: '@App\Service\PreferencesService'

when@dev:
    debug: true

when@test:
    twig:
        strict_variables: true
