services:

  sqldb:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: nrfc-fixtures-db
    env_file:
      - path: ./prod.env
        required: true
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  nginx:
    image: nginx
    container_name: nrfc-fixtures-nginx
    ports:
      - 8001:80
    volumes:
      - public:/opt/nrfcfixtures/public:ro
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - fixtures
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  fixtures:
    image: ghcr.io/tobybatch/nrfc-fixtures:fpm-prod
    container_name: nrfc-fixtures-prod
    env_file:
      - path: ./prod.env
        required: true
    depends_on:
      - sqldb
    volumes:
      - public:/opt/nrfcfixtures/public
      - var:/opt/nrfcfixtures/var
    restart: unless-stopped

volumes:
    database_data:
      name: nrfc-fixtures-prod-dbdata
    public:
      name: nrfc-fixtures-prod-public
    var:
      name: nrfc-fixtures-prod-var
